### PR TITLE
Enlarge story thumbnails and improve story list Material layout

### PR DESCRIPTION
**Pull request by mchowdhury**
I've improved the story layout by having the thumbnails to display to the side of the the story and have the indices integrated into the side as shown in the images below. Let me know your thoughts on the new layout!

Screenshot_20230709-154618
Screenshot_20230709-154631

### CODE REVIEW

**Comment by DeveloperPaul123** [comment]
Does this pull thumbnails from the actual stories? Or is it just the favicon from the website the story is posted on?

**Comment by mchowdhury** [comment]
@DeveloperPaul123 This is the favicons. In the app settings it is referred to as thumbnails

**Comment by mchowdhury** [comment]
This is still a WIP. Happy to have any assistance.
When you turn off thumbnails but keep numbered stories in the settings we need to revert to the old layout with a number in front of the title.

**Comment by DeveloperPaul123** [comment]
Ok, I see. 

I know you didn't' ask for my opinion, but I would say that it would be a better use of space if you were able to pull some sort of image from the article if the image is going to take up that much space in the row. Giving that much space to the favicon doesn't add much information (in my opinion) when scanning a list. 

Just my 2 cents. Ultimately it will be up to Simon to merge this.

**Comment by SimonHalvdansson** [comment]
Hey sorry about not looking into this earlier - been away on various things.

While I think this is cool - my main concern is the resolution and general quality of the thumbnails. This look gives the thumbnails quite a big focus, taking some focus away from the title. However the thunbnails are not very specialized to the content (e.g.. all GitHub is the same),  generally are not too well-designed because of their constraints, and are sometimes not background safe.

For these reasons I'm hesitant to further promote them in the app.

What @DeveloperPaul123 is saying about images from the website (e.g. pretty much all Reddit clients RIP) is something I've been interested in for a long time but never have got around to.

**Pull request closed without merging**
