### PR TITLE
Transparent status bar

### PR DESCRIPTION
**Pull request by fireph**
Works on stories list, comments, settings, and submissions activities.

Toggleable in the settings (true by default, but happy to make it false if you would prefer).

I haven't tested extensively on tablets yet, but seemed to work fine from my light testing.

Let me know if there is any part of this approach that you like to see different and I would be happy to change it. 🙂

https://github.com/SimonHalvdansson/Harmonic-HN/assets/443370/d1b64e49-6004-4645-84c2-3a8add57b200

### CODE REVIEW

**Comment by fireph** [comment]
The missing padding is fixed on the user submissions header in the newest commit

**Comment by SimonHalvdansson** [comment]
This looks like very nice work and it's very sweet of you to include the video :) I tried this at some point but decided against it because I didn't like how the clock in the status bar is hard to read. Also e.g. the Sync for Reddit and Twitter apps have background protection on the status bar and I think I want to keep it that way by default.

Still, it is very nice to have this as a toggeleable option because I know there are several others who like it this way.

I'm currently on vacation and don't have access to my development setup and I'd like to test things before merging this but if you change the default to being false and nothing pops up when I test this I'll merge this once I get back.

I'm sorry you had to dig through the quite hacky padding code but it sure looks like you made everything work out fine so good job!

**Comment by fireph** [comment]
> This looks like very nice work and it's very sweet of you to include the video :) I tried this at some point but decided against it because I didn't like how the clock in the status bar is hard to read. Also e.g. the Sync for Reddit and Twitter apps have background protection on the status bar and I think I want to keep it that way by default.
> 
> Still, it is very nice to have this as a toggeleable option because I know there are several others who like it this way.
> 
> I'm currently on vacation and don't have access to my development setup and I'd like to test things before merging this but if you change the default to being false and nothing pops up when I test this I'll merge this once I get back.
> 
> I'm sorry you had to dig through the quite hacky padding code but it sure looks like you made everything work out fine so good job! 

Sounds good, I'll update the default to false and double check that everyone works fine on tablets!

**Comment by SimonHalvdansson** [comment]
Things should be good now. While fixing the tablet version I got a slightly better view of how you did this and it looks good, thanks for you work!

**Pull request merged**
